spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  flyway:
    baseline-on-migrate: true
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
